DROP TABLE mm_movie_type CASCADE CONSTRAINTS;
DROP TABLE mm_pay_type CASCADE CONSTRAINTS;
DROP TABLE mm_member CASCADE CONSTRAINTS;
DROP TABLE mm_movie CASCADE CONSTRAINTS;
DROP TABLE mm_rental CASCADE CONSTRAINTS;
DROP SEQUENCE mm_rental_seq;